### ISSUE TITLE
关于03-JWT

### ISSUE THREAD

**Issue by x1angli** [coolshellx/articles#13]
问个比较弱的问题

> 尽可能采用 HTTPS，确保不被窃听。
> 如果存放在 Cookie 中则强烈建议开启 Http Only，其实官方推荐是放在 LocalStorage 里，然后通过 Header 头进行传递。

前面说HTTPS这个很好理解，后面为啥又说HTTP only？不是自相矛盾了么

**Comment by x1n0** [comment]
并不是，建议自行百度关键词：“cookie http only”

**Comment by imxfly** [comment]
Cookie 的 HTTP Only 这个 Flag 和 HTTPS 并不冲突，你会发现其实还有一个 Secure 的 Flag，这个就是指 HTTPS 了，这两个 Flag 互不影响的，开启 HTTP Only 会导致前端 JavaScript 无法读取该 Cookid，更多的是为了防止**类 XSS 攻击**。

**Comment by x1angli** [comment]
> Cookie 的 HTTP Only 这个 Flag 和 HTTPS 并不冲突，你会发现其实还有一个 Secure 的 Flag，这个就是指 HTTPS 了，这两个 Flag 互不影响的，开启 HTTP Only 会导致前端 JavaScript 无法读取该 Cookid，更多的是为了防止**类 XSS 攻击**。

原来如此，多谢了
换我是作者，我就起名“accessed by remote server only” 或者 "http(s) server only"

**Comment by imxfly** [comment]
哈哈，确实不能顾名思义，不过可以这么想：HttpOnly 就是指该 Cookie 就是为了只在 HTTP 请求中传递的，不能作为其他用途，也就是不能被 client-side's JavaScript 所操作，这么想会不会通顺一点。
