### ISSUE TITLE
关于标题

### ISSUE THREAD

**Issue by x1angli** [coolshellx/articles#6]
How.To.Set.Up.An.High.Efficient.Working.Enviornment

语法
a highly efficient work environment
或
a high-efficiency work environment

work environment
也可以用
workplace environment

因为
working environment是指“能玩得转的环境”（与“玩不转的环境”相对）或者“我正在写的环境”（与已经公开发表的环境相对）但不是指工作环境

**Comment by haoel** [comment]
good! I am going to fix this.

**Comment by x1angli** [comment]
> good! I am going to fix this.

还需要把“an” 改成“a”。“high”是辅音，并且发音
